# once per week (on Sunday at 00:00)
refresh_cryspibois_worker:
  cron: "0 0 * * 0"
  class: "RefreshCryspiboisWorker"
  queue: default

# once per day at midnight
refresh_market_coins_worker:
  cron: "0 0 * * *"
  class: "RefreshMarketCoinsWorker"
  queue: default

# once per minute
refresh_base_currencies_worker:
  cron: "*/1 * * * *"
  class: "RefreshBaseCurrenciesWorker"
  queue: default

# once per 1 minute
broadcast_market_coins_worker:
  cron: "*/1 * * * *"
  class: "BroadcastMarketCoinsWorker"
  queue: default
